## packages to open on startup (used for functions)
library(dplyr)
library(plyr)
library(lme4)
library(AICcmodavg)
library(chron)
library(ggplot2)
library(gridExtra)
library(doMC) 
library(pryr)
library(reshape)
library(glm2)

